import fs from "fs";

/**
	Returns a random rumber in range <min, max)
*/
export function randomInRange(range: Readonly<[min:number, max:number]>): number{
	const [min, max] = range;
	const minCeiled = Math.ceil(min);
	const maxFloored = Math.floor(max);
	return Math.floor(Math.random() * (maxFloored - minCeiled) + minCeiled);
}



const unicodeRange = [0, 1114111 +1] as const;
const asciiRange = [0, 255 +1] as const;

/**
	Constructs a random valid unicode string of provided length
	(can have broken surrogate pairs and such)
*/
export function randomUnicodeString(length: number): string {
	const toJoin: Array<string> = [];
	
	for(let i = 0; i < length; i++){
		toJoin.push(String.fromCodePoint(randomInRange(unicodeRange)));
	}

	return toJoin.join("");
}

export function randomAsciiString(length: number): string {
	const toJoin: Array<string> = [];
	
	for(let i = 0; i < length; i++){
		toJoin.push(String.fromCodePoint(randomInRange(asciiRange)));
	}

	return toJoin.join("");
	
}


/**
	Creates a new file based on given directory path and filename parameters.
    Writes the payload string to it.
	Appends a underscore followed by unique number to the end of filename so no
	two files generated by this function can possibly collide.


	If an error occured, returns false. Otherwise returns true.
	On error writes the payload to the console.
*/
let fileUniqueNumber = 0;
export function dumpStringToUniqueFile(dir: string, filename: string, payload: string): boolean {
	fileUniqueNumber += 1;

	//normalizing the dir trailing slash
	if (dir.slice(dir.length-1, dir.length) != '/'){
		dir += '/';
	}	

	const path: string = dir + filename + '_' + String(fileUniqueNumber);
	try {
		fs.mkdirSync(dir, { recursive: true });	
		fs.writeFileSync(path, payload);
	}catch (e){
		console.log(payload);
		return false;
	}


	return true;
}