/**
	Enum of ParseError union discriminators
	each entry in the enum corresponds with
	a specific ParseError variant.
*/
export enum ParseErrorKind {
	FOUND_ERROR_TOKENS,
	INDEX_OUT_OF_BOUNDS,
	STRING_NOT_VALID_JSON,
	STACK_OVERFLOW,
	WRONG_SYNTAX,
}

/**
	This namespace contains types for all specific variants of 
	ParseError. Each variant has a corresponding ParseErrorKind
	value as a discriminator.
*/
export namespace ParseErrorVariants {
	/**
		Reported when token tape given as input to the parser
		has erorr (or incomplete error) tokens.
		
		tokenIndexes array points to all detected error tokens in the tape.
	*/
	export type FoundErrorTokens = {
		kind: ParseErrorKind.FOUND_ERROR_TOKENS,
		tokenIndexes: Readonly<Array<number>>,
	}

	/**
		Reported when token tape given as input to the parser
		has index match tokens that exceed maximum permitted value.
		
		tokenIndexes array points to all detected invalid index tokens in the tape.
	*/
	export type IndexOutOfBounds = {
		kind: ParseErrorKind.INDEX_OUT_OF_BOUNDS,
		tokenIndexes: Readonly<Array<number>>,
	}

	/**
		Reported when token tape given as input to the parser
		has index match tokens that exceed maximum permitted value.
		
		tokenIndexes array points to all detected invalid index tokens in the tape.
	*/
	export type StringNotValidJson = {
		kind: ParseErrorKind.STRING_NOT_VALID_JSON,
		tokenIndexes: Readonly<Array<number>>,
	}
	

	/**
		Reported when parsing a constraint block in an expression
		exceeds platform's stack or recursion limit. 

		Token indexes array contains a last token attempted to parse before
		the eror appeared.
	*/
	export type StackOverflow = {
		kind: ParseErrorKind.STACK_OVERFLOW,
		tokenIndexes: Readonly<Array<number>>,
	}


	

	/**
		SUBJECT TO CHANGE
	*/
	export type WrongSyntax = {
		kind: ParseErrorKind.WRONG_SYNTAX,
		tokenIndexes: Readonly<Array<number>>,
	}
}

/**
	Tagged union of all error types,
	uses field (kind: ParseErrorKind) as union discriminator.
*/
export type ParseError = Readonly<
	ParseErrorVariants.FoundErrorTokens 
	| ParseErrorVariants.IndexOutOfBounds
	| ParseErrorVariants.StringNotValidJson
	| ParseErrorVariants.StackOverflow
	| ParseErrorVariants.WrongSyntax
>;



/**
	Incomplete error type that may be generated by parser functions
	It includes filtered token indexes and must be transformed into
	a proper error later via inverse index mapping using 
	parseErrorFromIncomplete function.
*/
export type IncompleteParseError = {
	targetKind: ParseErrorKind,
	filteredTokenIndexes: Readonly<Array<number>>,
}
/**
	Transforms an incomplete errors array into a proper parse error instances
	via inverse index mapping from filtered to original token tape tokens.
*/
export function parseErrorsFromIncomplete(
	incomplete: Readonly<Array<IncompleteParseError>>,
	tokenMapping: Readonly<Array<number>>,
): Array<ParseError> {
	const result = new Array(incomplete.length);
	for (let errIdx = 0; errIdx < incomplete.length; errIdx++){
		const err: IncompleteParseError = incomplete[errIdx];
		const indexCount = err.filteredTokenIndexes.length;

		const indexesCorrect: Array<number> = new Array(indexCount);
		for (let i = 0; i < indexCount; i++){
			indexesCorrect[i] = tokenMapping[err.filteredTokenIndexes[i]];
		}
		const properError: ParseError = {
			kind: err.targetKind,
			tokenIndexes: indexesCorrect, 
		}
		result[errIdx] = properError;
	}
	return result;
}

